"""Definitions for go-eController sensors exposed via MQTT."""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    SIGNAL_STRENGTH_DECIBELS,
    UnitOfElectricCurrent,
    UnitOfPower,
    UnitOfEnergy
)
from homeassistant.helpers.entity import EntityCategory

from . import GoEControllerEntityDescription

_LOGGER = logging.getLogger(__name__)


@dataclass
class GoEControllerSensorEntityDescription(GoEControllerEntityDescription, SensorEntityDescription):
    """Sensor entity description for go-eController."""

    domain: str = "sensor"


def remove_quotes(value, unused) -> str:
    """Remove quotes helper."""
    return value.replace('"', "")


def extract_isv(value: str, key: tuple) -> float:
    """Extract isv values from list."""
    list_int, dict_key = key
    if dict_key in ["i", "p"]:
        return round(float(json.loads(value)[int(list_int)][dict_key]), 1)
    if dict_key == "f":
        return round(float(json.loads(value)[int(list_int)][dict_key]) * 100)


def extract_ccp(value: str, key: str) -> float:
    """Extract ccp values from list."""
    try:
        return round(float(json.loads(value)[int(key)]))
    except TypeError:
        return 0


def extract_cec(value: str, key: tuple) -> float:
    """Extract cec values from list."""
    list_int, sub_int = key
    try:
        return round(float(json.loads(value)[int(list_int)][int(sub_int)]), 1)
    except TypeError:
        return 0


SENSORS: tuple[GoEControllerSensorEntityDescription, ...] = (
    GoEControllerSensorEntityDescription(
        key="isv_1_i",
        topic="isv",
        attribute=("0", "i"),
        name="Amp 1",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_2_i",
        topic="isv",
        attribute=("1", "i"),
        name="Amp 2",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_3_i",
        topic="isv",
        attribute=("2", "i"),
        name="Amp 3",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_4_i",
        topic="isv",
        attribute=("3", "i"),
        name="Amp 4",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_5_i",
        topic="isv",
        attribute=("4", "i"),
        name="Amp 5",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_6_i",
        topic="isv",
        attribute=("5", "i"),
        name="Amp 6",
        state=extract_isv,
        device_class=SensorDeviceClass.CURRENT,
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_1_p",
        topic="isv",
        attribute=("0", "p"),
        name="Power 1",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_2_p",
        topic="isv",
        attribute=("1", "p"),
        name="Power 2",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_3_p",
        topic="isv",
        attribute=("2", "p"),
        name="Power 3",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_4_p",
        topic="isv",
        attribute=("3", "p"),
        name="Power 4",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_5_p",
        topic="isv",
        attribute=("4", "p"),
        name="Power 5",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_6_p",
        topic="isv",
        attribute=("5", "p"),
        name="Power 6",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_1_f",
        topic="isv",
        attribute=("0", "f"),
        name="Power Factor 1",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_2_f",
        topic="isv",
        attribute=("1", "f"),
        name="Power Factor 2",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_3_f",
        topic="isv",
        attribute=("2", "f"),
        name="Power Factor 3",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_4_f",
        topic="isv",
        attribute=("3", "f"),
        name="Power Factor 4",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_5_f",
        topic="isv",
        attribute=("4", "f"),
        name="Power Factor 5",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="isv_6_f",
        topic="isv",
        attribute=("5", "f"),
        name="Power Factor 6",
        state=extract_isv,
        device_class=SensorDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_home",
        topic="ccp",
        attribute="0",
        name="Power (home)",
        state=extract_ccp,
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_grid",
        topic="ccp",
        name="Power (grid)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="1",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_car",
        topic="ccp",
        name="Power (car)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="2",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_relay",
        topic="ccp",
        name="Power (relay)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="3",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_solar",
        topic="ccp",
        name="Power (solar)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="4",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_battery",
        topic="ccp",
        name="Power (battery)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="5",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_1",
        topic="ccp",
        name="Power (custom 1)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="6",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_2",
        topic="ccp",
        name="Power (custom 2)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="7",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_3",
        topic="ccp",
        name="Power (custom 3)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="8",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_4",
        topic="ccp",
        name="Power (custom 4)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="9",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_5",
        topic="ccp",
        name="Power (custom 5)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="10",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_6",
        topic="ccp",
        name="Power (custom 6)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="11",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_7",
        topic="ccp",
        name="Power (custom 7)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="12",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_8",
        topic="ccp",
        name="Power (custom 8)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="13",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_9",
        topic="ccp",
        name="Power (custom 9)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="14",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="ccp_custom_10",
        topic="ccp",
        name="Power (custom 10)",
        device_class=SensorDeviceClass.POWER,
        native_unit_of_measurement=UnitOfPower.WATT,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=True,
        disabled=False,
        attribute="15",
        state=extract_ccp,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_home_in",
        topic="cec",
        attribute=("0","0"),
        name="Energy in (home)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_home_out",
        topic="cec",
        attribute=("0","1"),
        name="Energy out (home)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_grid_in",
        topic="cec",
        attribute=("1","0"),
        name="Energy in (grid)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_grid_out",
        topic="cec",
        attribute=("1","1"),
        name="Energy out (grid)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_car_in",
        topic="cec",
        attribute=("2","0"),
        name="Energy in (car)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_car_out",
        topic="cec",
        attribute=("2","1"),
        name="Energy out (car)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_relay_in",
        topic="cec",
        attribute=("3","0"),
        name="Energy in (relay)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_relay_out",
        topic="cec",
        attribute=("3","1"),
        name="Energy out (relay)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_solar_in",
        topic="cec",
        attribute=("4","0"),
        name="Energy in (solar)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_solar_out",
        topic="cec",
        attribute=("4","1"),
        name="Energy out (solar)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_battery_in",
        topic="cec",
        attribute=("5","0"),
        name="Energy in (battery)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_battery_out",
        topic="cec",
        attribute=("5","1"),
        name="Energy out (battery)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_1_in",
        topic="cec",
        attribute=("6","0"),
        name="Energy in (custom 1)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_1_out",
        topic="cec",
        attribute=("6","1"),
        name="Energy out (custom 1)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_2_in",
        topic="cec",
        attribute=("7","0"),
        name="Energy in (custom 2)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_2_out",
        topic="cec",
        attribute=("7","1"),
        name="Energy out (custom 2)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_3_in",
        topic="cec",
        attribute=("8","0"),
        name="Energy in (custom 3)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_3_out",
        topic="cec",
        attribute=("8","1"),
        name="Energy out (custom 3)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_4_in",
        topic="cec",
        attribute=("9","0"),
        name="Energy in (custom 4)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_4_out",
        topic="cec",
        attribute=("9","1"),
        name="Energy out (custom 4)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_5_in",
        topic="cec",
        attribute=("10","0"),
        name="Energy in (custom 5)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_5_out",
        topic="cec",
        attribute=("10","1"),
        name="Energy out (custom 5)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_6_in",
        topic="cec",
        attribute=("11","0"),
        name="Energy in (custom 6)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_6_out",
        topic="cec",
        attribute=("11","1"),
        name="Energy out (custom 6)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_7_in",
        topic="cec",
        attribute=("12","0"),
        name="Energy in (custom 7)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_7_out",
        topic="cec",
        attribute=("12","1"),
        name="Energy out (custom 7)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_8_in",
        topic="cec",
        attribute=("13","0"),
        name="Energy in (custom 8)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_8_out",
        topic="cec",
        attribute=("13","1"),
        name="Energy out (custom 8)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_9_in",
        topic="cec",
        attribute=("14","0"),
        name="Energy in (custom 9)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_9_out",
        topic="cec",
        attribute=("14","1"),
        name="Energy out (custom 9)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_10_in",
        topic="cec",
        attribute=("15","0"),
        name="Energy in (custom 10)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="cec_custom_10_out",
        topic="cec",
        attribute=("15","1"),
        name="Energy out (custom 10)",
        state=extract_cec,
        device_class=SensorDeviceClass.ENERGY,
        native_unit_of_measurement=UnitOfEnergy.WATT_HOUR,
        state_class=SensorStateClass.TOTAL_INCREASING,
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="fwv",
        name="Firmware version",
        entity_category=EntityCategory.DIAGNOSTIC,
        state=remove_quotes,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=None,
        icon="mdi:numeric",
        entity_registry_enabled_default=False,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="rbc",
        name="Reboot counter",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=SensorStateClass.TOTAL_INCREASING,
        icon="mdi:counter",
        entity_registry_enabled_default=True,
        disabled=False,
    ),
    GoEControllerSensorEntityDescription(
        key="rbt",
        name="Uptime",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=None,
        native_unit_of_measurement=None,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=True,
        disabled_reason="TODO: Convert to a timestamp first",
    ),
    GoEControllerSensorEntityDescription(
        key="rssi",
        name="WiFi signal strength",
        entity_category=EntityCategory.DIAGNOSTIC,
        device_class=SensorDeviceClass.SIGNAL_STRENGTH,
        native_unit_of_measurement=SIGNAL_STRENGTH_DECIBELS,
        state_class=SensorStateClass.MEASUREMENT,
        entity_registry_enabled_default=False,
        disabled=False,
    ),
)
